version: "3.9"

services:
  api:
    build: .
    container_name: taxia-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
